### ISSUE TITLE
ContainerView is changing to white during tranistion

### ISSUE THREAD

**Issue by m1entus** [MoZhouqi/KMNavigationBarTransition#3]
Hi, i presented view controller using blur effect on background, so i wanted to all view controllers have clearColor, during `- (void)km_viewWillLayoutSubviews {` you are setting containerView to background color and my presented controllers looks ugly, do you really need to set background color to white color?

**Comment by MoZhouqi** [comment]
If I don't set the background color of the container view, the navigation bar will look ugly when transitioning if the navigation bar is translucent, you can try it in the demo. To solve this problem, I can set the background color of `self.navigationController.navigationBar.superview` or `self.view.window` to white color, instead of setting the background color of the container view,  or add a global variable to decide whether you need to set the background color. Do you have any idea?

**Comment by m1entus** [comment]
I would make category for UINavigationController and make getter for background color for container view, and then would be easy to override in each UINavigationController subclass, because UINavigationControleller can always ask topViewController for it if needed.

**Comment by m1entus** [comment]
btw. I have check transitioning if navigation bar is translucent on your demo and i don't see any issue and ugly looking navigation bar on it .. ?

**Comment by MoZhouqi** [comment]
The color on the right side of the navigation bar is darker when transitioning.

![simulator screen shot jan 19 2016 10 56 08 am](https://cloud.githubusercontent.com/assets/7426363/12408454/8bbe2054-be9b-11e5-815c-6ce7cdec97df.png)

**Comment by MoZhouqi** [comment]
Hi, I will close the issue, if you have any further questions, please feel free to reopen it.

**Comment by m1entus** [comment]
But this is still a issue could you gix that and add property for color in your navigation controller category?
