### ISSUE TITLE
[Feature Request] add ability to enable or disable transition

### ISSUE THREAD

**Issue by tinpont** [MoZhouqi/KMNavigationBarTransition#57]
This is not a very common case. But it's good to let user control this transition affect or not.

I see the `WeChat` app has two type of navigation bar transition. The original navigation transition and the other one just like this project(WeChat -> Me -> Cards & Offers).

Should we add a switch for this transition?

**Comment by MoZhouqi** [comment]
Hi @tinpont, I didn't add the switch because I tried to make the library cover all cases. As the mini program of WeChat, all the animation transitions are similar to the effects provided by this library.

But adding a switch that gives users more control,  so feel free to make a pull request if you want.

**Comment by tinpont** [comment]
Thanks for your reply, @MoZhouqi. I will try when I have time.
